services:
  frontend:
    container_name: "frontend"
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
      - storage

  backend:
    container_name: "backend"
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - rabbit_mq

    command: >
      sh -c "
      migrate -path db/migration -database 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable' --verbose up
      && ./main
      "

  storage:
    container_name: "storage"
    build: ./storage
    restart: unless-stopped
    volumes:
      - storage_data:/app/files
    ports:
      - "8081:8081"
    env_file:
      - .env

  db:
    container_name: "db"
    restart: unless-stopped
    image: postgres:12.17-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  rabbit_mq:
    container_name: "rabbit_mq"
    image: "rabbitmq:3.12.13-management-alpine"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5672:5672" 
      - "15672:15672"

  caddy:
    container_name: "caddy"
    image: "caddy:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db_data:
    name: "db_data"
  storage_data:
    name: "storage_data"
  rabbitmq_data:
    name: "rabbitmq_data"
  rabbitmq_log:
    name: "rabbitmq_log"
  caddy_data:
    name: "caddy_data"
  caddy_config:
    name: "caddy_config"

