version: '3.8'

services:
  frontend:
    container_name: "frontend"
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
      storage:
        condition: service_healthy

  backend:
    container_name: "backend"
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy

    command: >
      sh -c "
      migrate -path db/migration -database 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable' --verbose up
      && ./main
      "

  storage:
    container_name: "storage"
    build: ./storage
    volumes:
      - storage_data:/app/files
    ports:
      - "8081:8081"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  db:
    container_name: "db"
    image: postgres:12.17-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  
  rabbit_mq:
    container_name: "rabbit_mq"
    image: "rabbitmq:3.12.13-management-alpine"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672" 
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    container_name: "caddy"
    image: "caddy:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db_data:
    name: "db_data"
  storage_data:
    name: "storage_data"
  rabbitmq_data:
    name: "rabbitmq_data"
  rabbitmq_log:
    name: "rabbitmq_log"
  caddy_data:
    name: "caddy_data"
  caddy_config:
    name: "caddy_config"
